services:
  frontend:
    build: ./frontend
    container_name: vue_app
    ports:
      - "8080:80"  # Producción con NGINX
    depends_on:
      - backend
    networks:
      - app-network
  
  backend:
    build: ./backend
    container_name: node_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: pg_database
    ports:
      - "2345:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pg_data:

networks:
  app-network:
    driver: bridge
